fullnameOverride: reservation-microservice

image:
  repository: kirillovav1/reservation
  tag: v3
  pullPolicy: IfNotPresent

existingSecret: auth0-env

service:
  enabled: true
  type: ClusterIP
  port: 8070
  targetPort: 8070

env:
  DB_DSN: postgresql://program:test@postgres-lab5-postgresql:5432/reservations

