fullnameOverride: loyalty-microservice

image:
  repository: kirillovav1/loyalty
  tag: lab5
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: ClusterIP
  port: 8050
  targetPort: 8050

env:
  DB_DSN: postgresql://program:test@postgres-postgresql:5432/loyalties


