fullnameOverride: gateway-worker

image:
  repository: kirillovav1/gateway
  tag: v3
  pullPolicy: IfNotPresent

existingSecret: auth0-env

service:
  enabled: false

env:
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: program
  RABBITMQ_PASSWORD: test

command:
  - python
  - -m
  - app.consumer

resources: {}

