fullnameOverride: loyalty-microservice

image:
  repository: kirillovav1/loyalty
  tag: v3
  pullPolicy: IfNotPresent

existingSecret: auth0-env

service:
  enabled: true
  type: ClusterIP
  port: 8050
  targetPort: 8050

env:
  DB_DSN: postgresql://program:test@postgres-lab5-postgresql:5432/loyalties


